#! /bin/sh

HERE=$(cd ${0%/*} && pwd)
ROOTDIR=${HERE%/*}
EMU=beam
BINDIR=$ROOTDIR/{{erts_vsn}}/bin
cd $ROOTDIR
export ROOTDIR
export EMU
export BINDIR

NODENAME=${NODENAME-erel_master}

exec $BINDIR/erlexec -mode embedded -config $ROOTDIR/releases/{{rel_vsn}}/sys -boot $ROOTDIR/releases/{{rel_vsn}}/erel_master -name $NODENAME -erel_master dir \"$ROOTDIR/data\" -noshell $@
