#! /bin/sh

realpath() {
      [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}


CONFIG=`realpath $2`
HERE=$(cd ${0%/*} && pwd)
ROOTDIR=${HERE%/*}
EMU=beam
BINDIR=$ROOTDIR/{{erts_vsn}}/bin
cd $ROOTDIR
export ROOTDIR
export EMU
export BINDIR

tail=${@:3:$((${#@} - 1))}

exec $BINDIR/erlexec -mode embedded -config $ROOTDIR/releases/{{rel_vsn}}/sys -boot $ROOTDIR/releases/{{rel_vsn}}/erel_manager -noshell -s erel_manager_main $1 -erel_manager config \"$CONFIG\" $tail
